### ISSUE TITLE
[FEATURE] Toggleable ISBN Filtering

### ISSUE THREAD

**Issue by LilAttacker** [UNLV-CS472-672/2024-F-GROUP1-Tabby#85]
# Priority
- [ ] Required
- [ ] Important
- [X] Nice to Have
- [ ] None of the Above

## Is your feature request related to a problem? Please describe.
Not all books have an ISBN 13, especially popular older books, and our system currently filters all of these out when searching. This can make it quite pathetic in some cases when identifying or recommending books.

## Describe the solution you'd like
Make it toggleable or expand the filter to include all of ISBN instead of just 13.

### Additional context
This seems to make recommendations go for more obscure recent books that have an ISBN 13 instead of relevant popular ones that might not.

**Comment by caesarx26** [comment]
Shouldn't you guys just expand to include isbn 10 if that is causing issues? The way I store books the isbn field can be any length they each get their own unique ID regardless that I make. For the search I remove any dashes from the search and use regex expression to see if the search without the dashes is an isbn 10 or 13 number if it is I do the search with just isbn otherwise I just use phrase to find the book. The search could be better but at least it works when searching for the book directly it's more the recommendations API call that should be fixed

**Comment by caesarx26** [comment]
If you want me to toggle it you can add a query parameter to do so?

**Comment by LilAttacker** [comment]
A toggle feature is added in #82. I think expanding it to all ISBN types is the best, but it was decided early on only to accept ISBN 13, so backend has been filtering based on that requirement.
